import React from "react";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import "./bootstrap.custom.min.css";
import {ConstantLayout} from "@/app/ConstantLayout";
import {SideBar} from "@/components/constantLayout/sidebar/SideBar";
import {UserProvider} from "@/app/UserProvider";

const inter = Inter({subsets: ["latin"]}
);

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{ children: React.ReactNode;}>) {

    return (
        <html lang="uk-UA">
        <body>
        <UserProvider >
            <ConstantLayout>
                <SideBar/>
                <main id="app-content">
                    <h1>11111111111 1111111 1111111111 1111111111 111111111 11111111111111 111111111 1111111 11111 11111 11111111111 111111111111 11111111111 11111111 1111111 11111111111111 11111111 1111111111111 11111111 1111111 1111111111 11111111 11111111 1111 111111</h1>
                    {children}
                </main>
            </ConstantLayout>
        </UserProvider>
        </body>
        </html>
    );
}
